name: Build website
on:
  workflow_call:
    inputs:
      dest-image-suffix:
        type: string
        description: >
          Destination image suffix for the GHCR.
          Defaults to the repository name in lowercase.
        default: ""


jobs:
  hakyll-site-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout action repo
        uses: actions/checkout@v3
        with:
          repository: MatthiasValvekens/gha-hakyll-build
          ref: ${{ github.job_workflow_sha }}
          path: .build-workflow
      - name: Set image name
        id: set-image
        run: |
          if [[ -z "$SUFFIX" ]]; then
            echo "image=${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"
          else
            echo "image=$SUFFIX" >> "$GITHUB_OUTPUT"
          fi
        env:
          SUFFIX: ${{ inputs.dest-image-suffix }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure dynamic action
        run: |
          sed "s|:IMAGE_TAG|$TAG|" < .build-workflow/_action.yml > .build-workflow/action.yml
        env:
          TAG: ghcr.io/${{ steps.set-image.outputs.image }}
      - name: Build website
        uses: ./.build-workflow
      - name: Upload generated content
        uses: actions/upload-artifact@v3
        with:
          name: website-content
          path: _site/
