name: Publish site builder image
on:
  workflow_call:
    inputs:
      ghc-version:
        type: string
        description: GHC version
        required: true
      dest-image-suffix:
        type: string
        description: >
          Destination image suffix for the GHCR.
          Defaults to the repository name in lowercase.
        default: ""
    outputs:
      image-tag:
        value: ${{ jobs.publish-builder.outputs.image-tag }}

jobs:
  publish-builder:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    outputs:
      image-tag: ${{ fromJSON(steps.docker-meta.outputs.json).tags[0] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout action repo
        uses: actions/checkout@v3
        with:
          repository: MatthiasValvekens/gha-hakyll-build
          ref: ${{ github.job_workflow_sha }}
          path: .build-workflow
      - name: Set image name
        id: set-image
        run: |
          if [[ -z "$SUFFIX" ]]; then
            echo "image=${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"
          else
            echo "image=$SUFFIX" >> "$GITHUB_OUTPUT"
          fi
        env:
          SUFFIX: ${{ inputs.dest-image-suffix }}
      - id: docker-meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: |
            ghcr.io/${{ steps.set-image.outputs.image }}
          tags: |
            type=raw,value=latest
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .build-workflow/Dockerfile
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          build-args: |
            GHC_VERSION=${{ inputs.ghc-version }}
